command! Jovi echo 
\"Happy using JOVI Vim configuration!!!\n"
\"\n"
\"Useful commands:\n"
\":GitGutterToggle           - Toggle the git diff feature\n"
\"   ]h                      - Next hunk\n"
\"   [h                      - Previous hunk\n"
\"   <leader>hu                     - Undo an individual hunk\n"
\"\n"
\"<leader>tm                        - Toggle the table mode\n"
\"\n"
\"Highlighter:\n"
\"   f<CR>                   - Set\n"
\"   f<BS>                   - Erase\n"
\"   f<C-L>                  - Clear\n"
\"   :Hi + pattern           - Manualy set a pattern\n"
